#!/bin/sh

#set env dir, all env setting go here
export ENV_DIR=~/env/

#start xbindkeys
xbindkeys &
#start dropbox
#dropbox &
#reset wallpaper
sh ~/.fehbg &
#dwm status bar
sh $ENV_DIR/linux-env/scripts/dwm-bar.sh 
#mate monitor settings
/usr/lib/mate-settings-daemon/mate-settings-daemon &

#finally start wm
#exec dwm
exec i3


