#!/bin/sh

#set env dir, all env setting go here
export ENV_DIR=~/env/

#start xbindkeys
xbindkeys &
#start dropbox
dropbox &
#dwm status bar
#sh $ENV_DIR/linux-env/scripts/dwm-bar.sh fix me -> put to home 
#mate monitor settings
/usr/lib/mate-settings-daemon/mate-settings-daemon &

#wallpaper
feh --bg-scale ~/.config/wallpaper.png &

#finally start wm
#exec dwm
exec i3 

